apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc_helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc_helloworld
  template:
    metadata:
      labels:
        app: poc_helloworld
    spec:
      containers:
      - name: poc_helloworld
        image: poc_helloworld:latest
      imagePullSecrets:
      - name: nexus-secret
---
apiVersion: v1
kind: Service
metadata:
  name: poc_helloworld
spec:
  selector:
    app: poc_helloworld
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
